### ISSUE TITLE
hadoop 3.2, issue with Yarn Api for State & FinishedTimeBegin

### ISSUE THREAD

**Issue by sun5147** [CODAIT/hadoop-yarn-api-python-client#100]
Hi, we are using yarn as RM for running spark jobs and we use the Yarn API to verify the status of jobs submitted to Yarn. 
we query the Api based on the state & FinishedTimeBeing. In Hadoop-yarn 2.8, this was allowed and we are running fine. 

Recently, we have upgraded our infastructure to Hadoop 3.2 and this query is not working anymore. 

we are able to query using either Time or Status but not both. Is there an open issue around this ?

any help on this would be greatly appreciated.

**Comment by dimon222** [comment]
Hm, based on existing logic the library is just doing pass through request, so perhaps that might be regression of YARN itself.
What is the exact Hadoop patch version you refer to? 3.2.1 ?

**Comment by sun5147** [comment]
Hi Dimon,

yes, we are on 3.2.1

**Comment by dimon222** [comment]
Try trace the request being made with this logger configured on top of your python script
```
import logging
logging.basicConfig(level=logging.DEBUG)
```
If it contains both parameters, then I would guess it's YARN regression. I know that Apache released 3.2.2 recently, worth a check there.

**Comment by dimon222** [comment]
Just wanted to check if you figured the solution

**Comment by dimon222** [comment]
Closing due to no response.
