### ISSUE TITLE
Simple authentication is not supported

### ISSUE THREAD

**Issue by dimon222** [CODAIT/hadoop-yarn-api-python-client#105]
Based on https://github.com/jupyter/enterprise_gateway/issues/979

Implementation details:
https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/HttpAuthentication.html

Options:
1. Easy - add argument to allow username being passed as part of configs/constructors
2. Fancy - implement custom Auth that would replicate this. Might require more efforts, but sounds like interesting task to do.

**Comment by kevin-bates** [comment]
Thanks for opening this issue Dmitry.  When I poked at this earlier, I was hopeful that we could leverage the Auth parameter somehow, so I'm inclined to take the option 2 route.  This custom Auth class (would we refer to it as "simple auth" based on your link?) would live in this package and be available to applications taking that approach - correct?

**Comment by dimon222** [comment]
>  This custom Auth class (would we refer to it as "simple auth" based on your link?) would live in this package and be available to applications taking that approach - correct?
This is correct

**Comment by abzymeinsjtu** [comment]
> This custom Auth class (would we refer to it as "simple auth" based on your link?) would live in this package and be available to applications taking that approach - correct?

thx for kevin and dimon. i just review the code in this package and find no implementation of an auth class. so would this custom auth class live in this package or a third one(e.g. HTTPKerberosAuth in requests_kerberos) may be better

**Comment by kevin-bates** [comment]
Your code analysis is correct - the current auth-based classes derive from other sources.  However, because this would be a special case relative to this package, I think it makes sense that this package supply a "simple auth" option for clients to leverage.
