### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by daniel-dylag-openx** [CODAIT/hadoop-yarn-api-python-client#108]
Hi,
in my organization the Hadoop cluster is in an internal network in GCP and access to VM ports from developer's machine is only possible via SOCKS proxy.

If you can connect directly you can just do this:
```
hs = HistoryServer('http://my-history-server:19888')
app_information = hs.application_information()
```
With SOCKS the only way to get this response is to use lower level method:
```
hs = HistoryServer('http://my-history-server:19888')
app_information = hs.request('/ws/v1/history/info', proxies=dict(http='socks5h://socks-proxy:1080'))
```
But I would like to be able to just call it like this:
```
hs = HistoryServer('http://my-history-server:19888', proxies=dict(http='socks5h://socks-proxy:1080'))
app_information = hs.application_information()
```

**Comment by dimon222** [comment]
Good idea. I will have a look once I get back to my machine.
