### ISSUE TITLE
Fix docs link at top GitHub repo

### ISSUE THREAD

**Issue by kevin-bates** [CODAIT/hadoop-yarn-api-python-client#62]
The docs link at the very top of the repository's page still references the old readthedocs site.  It should be updated to https://readthedocs.org/projects/yarn-api-client-python per the changes in #59.

@toidi - I think you may be the only one that can edit that information, so I'm assigning this to you for now.

**Comment by dimon222** [comment]
Also same thing applies to Pypi repository description.

**Comment by kevin-bates** [comment]
> Also same thing applies to Pypi repository description.

@dimon222 - the pypi repo looks good to me - could you please check again?  I suspect Eduard updated it already.

**Comment by dimon222** [comment]
Same, looks good for me :+1:

**Comment by kevin-bates** [comment]
I've updated the doc link on the new repo location and pypi looks good.  Closing.
