### ISSUE TITLE
A better place for the repository

### ISSUE THREAD

**Issue by toidi** [CODAIT/hadoop-yarn-api-python-client#74]
Hi there and Happy New Year 🎉,

I want to bring up a discussion about a better place for the repository.

Since I'm not actively participating in the repository life, I believe there's a better place for it.

Where new contributors will join the project or maybe a parent project that will take care of the repository.

I'm open for any suggestions.

**Comment by toidi** [comment]
Perhaps, https://github.com/jupyter

**Comment by kevin-bates** [comment]
Happy New Year to you as well @toidi!

Yes, @lresende and I have talked about this and I think we'll have a location soon.  I believe Luciano returns from holiday next week, so we should have an update then.

Thank you for suggesting this and all the work you've done - its a very useful package!

**Comment by lresende** [comment]
@toidi, I have couple places I could suggest for the new home of this repo:
- https://github.com/elyra-ai empty for now, but this org will host a new project that we are going to open source soon
- https://github.com/codait which is an org we use for a few projects from our group
- https://github.com/xxx or we could create a new org for the project

Moving this to Jupyter might be undesirable, and would be a similar scenario as lumino, as they created a different org as it was a more generic framework, and not specific to jupyter. 

Any thoughts ?

**Comment by lresende** [comment]
@toidi Any thoughts on the suggestions above?

**Comment by toidi** [comment]
https://github.com/codait looks nice

**Comment by lresende** [comment]
@toidi do you want to transfer the repository to the codait org then? 
I have admin access and can accept it.

**Comment by toidi** [comment]
I can't
Looks like I need permission to create public repos in codait

<img width="987" alt="Screen Shot 2020-01-21 at 11 18 01" src="https://user-images.githubusercontent.com/892861/72780099-be356d00-3c3f-11ea-8006-182c40dcdebd.png">

**Comment by lresende** [comment]
@toidi, sorry for that, once you accept the invitation to the org you should be good to go.

**Comment by toidi** [comment]
I've joined, but still no permission to create public repos

**Comment by kevin-bates** [comment]
Hi Eduard, please try again.  Luciano just made some changes.

**Comment by toidi** [comment]
done

**Comment by kevin-bates** [comment]
Thank you Eduard.  Could you please give Luciano and/or myself the ability to "Manage" the pypi repo as well? https://pypi.org/project/yarn-api-client/

**Comment by toidi** [comment]
yup, ✅
