### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by dimon222** [CODAIT/hadoop-yarn-api-python-client#79]
We have done some patches for new python versions and for some JSON body endpoints.
I think it's safe to assume that's it's time to release new version of library after we merge #67

**Comment by kevin-bates** [comment]
I agree.  I'm also working on #63 and would like to include the PR for that when available.  I'm having some difficulties with what appear to be multiple handlers getting involved, so just trying to work that out.

**Comment by kevin-bates** [comment]
I'm wondering if we should get the repo moved first and the release can be relative to that new location - or might that be disruptive?  I'm not that familiar with what all is involved in a move.
