### ISSUE TITLE
get the number of vcore for a given application

### ISSUE THREAD

**Issue by parisni** [CODAIT/hadoop-yarn-api-python-client#82]
hi

I didn´t find mention in the documentation of how to get the number of vcore used by a given application (as the yarn ui provide).
Does this support this feature ?

**Comment by dimon222** [comment]
Seems like you're looking for classic cluster_application method of RM
https://yarn-api-client-python.readthedocs.io/en/latest/resource_manager.html#yarn_api_client.resource_manager.ResourceManager.cluster_application
The response u will get back will contain allocatedVCores and vcoreSeconds

**Comment by parisni** [comment]
sounds good indeed ! thanks

**Comment by dimon222** [comment]
Perhaps this can be closed, not an issue

**Comment by kevin-bates** [comment]
Agreed - thanks for posting the information.
