### ISSUE TITLE
Uunexpected keyword argument 'address'

### ISSUE THREAD

**Issue by lucienfregosi** [CODAIT/hadoop-yarn-api-python-client#84]
Hi

I've just download this package and when I try to use it I got this following error message `unexpected keyword argument 'address'`

My command is `yarn_client --host <host_ip> --port 8088 nm info`

Don't understand why the code does not expect address at line 252 as address is defined just above.

**Comment by dimon222** [comment]
Try `--address` instead of `--host`

**Comment by dimon222** [comment]
Class constructors got updated argument names, perhaps that caused regression for cli part.
