### ISSUE TITLE
Compliance to Hadoop 3.3.1

### ISSUE THREAD

**Issue by dimon222** [CODAIT/hadoop-yarn-api-python-client#89]
As some people might be aware, around 2 months ago there was a stable release of Hadoop 3.3.0, where certain subset of apis was modified with new additional parameters, and few REST endpoints got added.

I'm currently in process of reviewing the changes in official Apache Hadoop YARN REST documentation, and it is to arrive in PRs soon.

- [x] Resource Manager (3.3.0) (in #90 )
- [x] Application Master (3.3.0) - no changes required
- [x] MR History Server (3.3.0) - no changes required
- [x] Node Manager (3.3.0) (in #91 )
- [x] Resource Manager (3.3.1) - no changes required
- [x] Application Master (3.3.1) - no changes required
- [x] MR History Server (3.3.1) - no changes required
- [x] Node Manager (3.3.1) - no changes required
- [x] Review and validate that it works
- [x] Release new hadoop-yarn-api version with new support for 3.3.1
- [x] Bump compatibility version in README to 3.3.1
- [x] (optional) Add compatibility matrix in README to point for user what yarn-api-version is compatible to what version

**Comment by lresende** [comment]
Good @dimon222, we are trying to wrap up the release of Toree that supports Spark 3.0 and next will look into EG + Spark 3.0 running on Yarn 3.3.x. Thank you for the help here.

**Comment by dimon222** [comment]
I've done direct comparison in git for documentation pages for respective components between latest revision of 3.2.1 and 3.3.0, implemented missing apis and prepared necessary adjustments for changed endpoints.
Overall changes are insignificant and mainly backward compatible.

I currently don't have environment available to do proper integration testing, hopefully somebody can assist. The related PRs for both NM and RM are up.

**Comment by kevin-bates** [comment]
Thank you Dmitry!  I agree, this is very good timing although at time when there's "well-timed" convergence of many things! :smile:  I apologize for the late response.

**Comment by lresende** [comment]
@dimon222 Sorry for the delay here, although the PRs you submitted looks ok I don't have any YARN 3.x system to test at the moment. What do we want to do with this regard? Bump the release up and merge the prs? Or wait a bit more? @kevin-bates any opinions here?

**Comment by kevin-bates** [comment]
I'm thinking we might as well merge #90 and #91 to master and, once we get a chance to exercise things, cut a 1.1 or 2.0 release.  Does that sound like a plan?  I'll hold off until we're on the same page.  (Looks like #90 needs an update with base.)

**Comment by dimon222** [comment]
I'm okay with meeting both. Until we test it on real environment, we could hold the release itself or make a "beta" release

**Comment by dimon222** [comment]
@kevin-bates let me know if u can assist on doing the last 4 tasks to close this issue. We haven't released for a while, and we're already out of date in releases. I'm thinking to go further into patch updates right after and look after Timeline api definition.

**Comment by dimon222** [comment]
I've been able to get my hands on cluster with 3.3.1 hadoop cluster where I was able to confirm some of functionality. The code difference for 3.2.x vs 3.3.0 is not much of a big jump in codebase (you can review the PRs that were merged), so I think its okay to accept this as is. Any new problems that will pop will be sorted in future hotfix releases.

**Comment by dimon222** [comment]
I will update this to support 3.3.1, and then proceed with next tasks up to release.

**Comment by dimon222** [comment]
Released under version 1.0.3
