### ISSUE TITLE
How can I create a custom resource scheduler in YARN fair scheduler with Python?

### ISSUE THREAD

**Issue by hamiaws2020** [CODAIT/hadoop-yarn-api-python-client#95]
I would like to create a custom scheduler in Apache Yarn, however as the basic language used is in JAVA, I'm wondering how can I do this using Python? may I use a particular API?

**Comment by kevin-bates** [comment]
Hi @hamiaws2020 - thank you for opening this issue.  This repository only provides access to YARN manager instances via the REST API using Python.  It doesn't provide a facility for implementing custom schedulers or other YARN manager instances.  This package is essentially a _client_ to the YARN services.

Unfortunately, I cannot find much information on how to go about implementing custom schedulers, I can only find support related to the built-in schedulers.
