### ISSUE TITLE
 Does the resource manager support operations after the cluster is integrated with kerberos

### ISSUE THREAD

**Issue by liguodong0315** [CODAIT/hadoop-yarn-api-python-client#97]
When I use yarn_api_clinet for python, I found that I can normally get the app information in the cluster after kerberos integration, but when I want to do the operation, I find that I can’t connect to the RM normally.

code:
kerberos_auth = HTTPKerberosAuth(mutual_authentication=REQUIRED,sanitize_mutual_error_response=False)
rm = yarn_api_client.resource_manager.ResourceManager(service_endpoints=[''http://resourcemanager-01:8088','http://resourcemanager-02:8088'],auth=kerberos_auth,verify=False)

def get_applicatoin(application):
    app_data = rm.cluster_application(application_id=application).data
    return dict(list(app_data.values())[0])

def kill_application(application):
    app_info = get_applicatoin(application)
    state = app_info["state"]
    if state == "RUNNING" and rm.cluster_application_kill(application_id=application):
        print(application+" KILL")
    else:
        print(application+" no")

Erroe:
/usr/local/lib/python2.7/dist-packages/requests_kerberos/kerberos_.py:160: NoCertificateRetrievedWarning: Requests is running with a non urllib3 backend, cannot retrieve server certificate for CBT
  NoCertificateRetrievedWarning)
No handlers could be found for logger "yarn_api_client.hadoop_conf"
Traceback (most recent call last):
  File "kill.py", line 12, in <module>
    rm = yarn_api_client.resource_manager.ResourceManager(service_endpoints=['http://resourcemanager-01:8088','http://resourcemanager-02:8088'],auth=kerberos_auth,verify=False)
  File "/usr/local/lib/python2.7/dist-packages/yarn_api_client/resource_manager.py", line 87, in __init__
    raise Exception("No active RMs found")
Exception: No active RMs found

**Comment by dimon222** [comment]
Well, it tried to reach mentioned RM, but it doesn't give signs of life, so its crashing.
Are you sure it's happening only if you enable kerberos on yarn cluster? Have you done `kinit` to get tickt before trying to run python command?

**Comment by liguodong0315** [comment]
> Well, it tried to reach mentioned RM, but it doesn't give signs of life, so its crashing.
> Are you sure it's happening only if you enable kerberos on yarn cluster? Have you done `kinit` to get ticket before trying to run python command?


My yarn cluster has enabled kerberos, but the link in service_endpoints must be written as https:// to recognize the normal RM, but my RM8088 page does not have the https protocol enabled; at this time, when you perform the kill app operation, you will be prompted 400 error

**Comment by dimon222** [comment]
You could give a try to requests_gssapi library for handshake instead of requests_kerberos, as it seems that underline warning is coming from this custom with method.

**Comment by liguodong0315** [comment]
problem solved

**Comment by kevin-bates** [comment]
Hi @liguodong0315 - it's great to hear you're moving forward and thank you for updating and closing the issue.  

If the resolution might be beneficial to others, it would be much appreciated if you're able to share what you did to solve this issue.  Thank you.
