### ISSUE TITLE
Abnormal judgment of Resourcemanager HA

### ISSUE THREAD

**Issue by langtu329** [CODAIT/hadoop-yarn-api-python-client#98]
requests Parameters allow_redirects=False need to be added

def check_is_active_rm(url, timeout=30, auth=None, verify=True):
    try:
        response = requests.get(url + "/cluster", timeout=timeout, auth=auth, verify=verify, **allow_redirects=False**)
    except requests.RequestException as e:
        log.warning("Exception encountered accessing RM '{url}': '{err}', continuing...".format(url=url, err=e))
        return False

**Comment by dimon222** [comment]
Wait, whats wrong with allowing redirect? I would assume it makes sense to have if you want to redirect to different domain.

**Comment by dimon222** [comment]
Any update?

**Comment by dimon222** [comment]
Closing due to no response.
